package com.phos.core.data.engine

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.phos.core.data.dao.AdherenceStat
import com.phos.core.data.model.SymptomLog
import java.io.File
import java.io.FileOutputStream
import java.time.format.DateTimeFormatter
import java.util.*

class ReportGenerator(private val context: Context) {

    /**
     * Generates a PDF report of health metrics.
     * @return The File object pointing to the generated PDF.
     */
    fun generate30DayReport(
        adherenceStats: List<AdherenceStat>,
        symptoms: List<SymptomLog>
    ): File {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
        val page = document.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        var yPos = 50f

        // Title
        paint.color = Color.BLACK
        paint.textSize = 24f
        paint.isFakeBoldText = true
        canvas.drawText("PHOS Health Report: Last 30 Days", 50f, yPos, paint)
        yPos += 40f

        // Adherence Section
        paint.textSize = 18f
        paint.isFakeBoldText = true
        canvas.drawText("Medication Adherence", 50f, yPos, paint)
        yPos += 25f
        
        paint.textSize = 14f
        paint.isFakeBoldText = false
        adherenceStats.forEach { stat ->
            val percentage = if (stat.total > 0) (stat.takenCount * 100 / stat.total) else 0
            canvas.drawText("${stat.medicationId}: $percentage% ($stat.takenCount/$stat.total taken)", 70f, yPos, paint)
            yPos += 20f
        }
        yPos += 20f

        // Symptoms Section
        paint.textSize = 18f
        paint.isFakeBoldText = true
        canvas.drawText("Symptom Trends", 50f, yPos, paint)
        yPos += 25f

        paint.textSize = 12f
        paint.isFakeBoldText = false
        symptoms.take(15).forEach { log ->
            canvas.drawText("${log.timestamp}: ${log.symptomName} (Severity: ${log.severity})", 70f, yPos, paint)
            yPos += 18f
        }

        // Footer
        paint.textSize = 10f
        paint.color = Color.GRAY
        canvas.drawText("Generated by PHOS on ${Date()}", 50f, 800f, paint)

        document.finishPage(page)

        // Save to file
        val file = File(context.cacheDir, "PHOS_Report_${System.currentTimeMillis()}.pdf")
        document.writeTo(FileOutputStream(file))
        document.close()

        return file
    }
}
